### ISSUE TITLE
Error in flex

### ISSUE THREAD

**Issue by solangepaz** [InitialDLab/XDB#2]
When i execute ./configure, i get this warning: "*** The installed version of Flex, /usr/bin/flex, is too old to use with PostgreSQL.*** Flex version 2.5.31 or later is required, but this is flex 2.6.0." and when i execute make, i get this error: "ERROR: `flex' is missing on your system. It is needed to create the file `scan.c'. You can either get flex from a GNU mirror site or download an official distribution of PostgreSQL, which contains pre-packaged flex output."
I have flex in version 2.6.0, bison in version 3.0.4 and postgresql in version 9.5.14.
You have any idea for this issue ?
Thanks.

**Comment by zzy7896321** [comment]
That's a bug with the configure file that came with PostgreSQL. If might want to change line 7210 of configure to

if echo "$pgac_flex_version" | sed 's/[.a-z]/ /g' | $AWK '{ if ($1 = 2 && ($2 > 5  || ($2 == 5 && $3 >= 31)))  exit 0; else exit 1;}'

**Comment by solangepaz** [comment]
It's solved, thanks.
