### ISSUE TITLE
Online aggregation queries

### ISSUE THREAD

**Issue by solangepaz** [InitialDLab/XDB#3]
Hi,
When i execute for example, query10_online.sql I have this error: 
```
ERROR:  syntax error at or near "("
LINE 1: SELECT ONLINE SUM(l_extendedprice * (1 - l_discount))
                         ^

```
I have set the environment variable **LD_LIBRARY_PATH=/usr/local/pgsql/lib**.
Can you help me to solved this issue ?

**Comment by zzy7896321** [comment]
Hi,

Did you set PATH=/usr/local/pgsql/bin:$PATH to include the compiled binary into PATH?

**Comment by solangepaz** [comment]
No, because when i set this PATH i have this error:
```
Command 'ls' is available in '/bin/ls'
The command could not be located because '/bin' is not included in the PATH environment variable.
ls: command not found
Command 'lesspipe' is available in the following places
 * /bin/lesspipe
 * /usr/bin/lesspipe
The command could not be located because '/bin:/usr/bin' is not included in the PATH environment variable.
lesspipe: command not found
Command 'dircolors' is available in '/usr/bin/dircolors'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
dircolors: command not found
Command 'ls' is available in '/bin/ls'
The command could not be located because '/bin' is not included in the PATH environment variable.
ls: command not found
```

**Comment by zzy7896321** [comment]
You might not want to set PATH to /usr/local/bin. Rather it should be prepended to PATH. Maybe try the following line:
export PATH=/usr/local/bin:$PATH

**Comment by solangepaz** [comment]
I have the same error with: **export PATH=/usr/local/bin:$PATH**

**Comment by solangepaz** [comment]
And when i set the **LD_LIBRARY_PATH=/usr/local/pgsql/lib** i have this:
` /usr/lib/postgresql/9.5/bin/psql: symbol lookup error: /usr/lib/postgresql/9.5/bin/psql: undefined symbol: PQsslInUse`

**Comment by solangepaz** [comment]
The issue is solved. Thanks

**Comment by zzy7896321** [comment]
Glad to hear that. I was just trying to replicate the issue but was unable to. I'll close this thread.
