### ISSUE TITLE
query7 online return 0 

### ISSUE THREAD

**Issue by solangepaz** [InitialDLab/XDB#4]
Hi, 
I am using TPC-H  with 10GB, and when i run online query 7 i get the result: 

```
 time (ms) | nsamples | nrejected |          sum           | rel. CI
-----------+----------+-----------+------------------------+---------
      2000 |        0 |      1445 | 0.00000000000000000000 |       0
```

**Comment by zzy7896321** [comment]
Hi there,

Could you post the query you used?

Thanks.

**Comment by solangepaz** [comment]
The query is:

```
\timing on
SELECT ONLINE SUM(l_extendedprice * (1 - l_discount))
FROM supplier, lineitem, orders, customer, nation n1, nation n2
WHERE   s_suppkey = l_suppkey
    AND o_orderkey = l_orderkey
    AND c_custkey = o_custkey
    AND s_nationkey = n1.n_nationkey
    AND c_nationkey = n2.n_nationkey
	AND n1.n_name = 'CHINA'
WITHTIME 240000 CONFIDENCE 95 REPORTINTERVAL 1000;
```

**Comment by zzy7896321** [comment]
I'm unable to reproduce your issue. Maybe you are missing some of the indexes? The following are the indexes I currently have (use \di to print out all the indexes):

                       List of relations
 Schema |           Name            | Type  | Owner  |  Table
--------+---------------------------+-------+--------+----------
 public | customer_c_mktsegment_idx | index | zyzhao | customer
 public | customer_c_nationkey_idx  | index | zyzhao | customer
 public | customer_pkey             | index | zyzhao | customer
 public | lineitem_l_orderkey_idx   | index | zyzhao | lineitem
 public | lineitem_l_orderkey_idx1  | index | zyzhao | lineitem
 public | lineitem_l_returnflag_idx | index | zyzhao | lineitem
 public | lineitem_l_shipdate_idx   | index | zyzhao | lineitem
 public | lineitem_l_suppkey_idx    | index | zyzhao | lineitem
 public | lineitem_pkey             | index | zyzhao | lineitem
 public | nation_n_name_idx         | index | zyzhao | nation
 public | nation_n_regionkey_idx    | index | zyzhao | nation
 public | nation_pkey               | index | zyzhao | nation
 public | orders_o_custkey_idx      | index | zyzhao | orders
 public | orders_o_orderdate_idx    | index | zyzhao | orders
 public | orders_pkey               | index | zyzhao | orders
 public | part_pkey                 | index | zyzhao | part
 public | partsupp_pkey             | index | zyzhao | partsupp
 public | partsupp_ps_suppkey_idx   | index | zyzhao | partsupp
 public | region_pkey               | index | zyzhao | region
 public | region_r_name_idx         | index | zyzhao | region
 public | supplier_pkey             | index | zyzhao | supplier
 public | supplier_s_nationkey_idx  | index | zyzhao | supplier

**Comment by solangepaz** [comment]
I have only these:
                        List of relations
 Schema |           Name            | Type  |  Owner   |  Table
--------+---------------------------+-------+----------+----------
 public | customer_c_mktsegment_idx | index | postgres | customer
 public | customer_c_nationkey_idx  | index | postgres | customer
 public | lineitem_l_orderkey_idx   | index | postgres | lineitem
 public | lineitem_l_orderkey_idx1  | index | postgres | lineitem
 public | lineitem_l_returnflag_idx | index | postgres | lineitem
 public | lineitem_l_shipdate_idx   | index | postgres | lineitem
 public | lineitem_l_shipdate_idx1  | index | postgres | lineitem
 public | lineitem_l_suppkey_idx    | index | postgres | lineitem
 public | nation_n_name_idx         | index | postgres | nation
 public | orders_o_custkey_idx      | index | postgres | orders
 public | supplier_s_nationkey_idx  | index | postgres | supplier

**Comment by zzy7896321** [comment]
I think the missing one is the index on supplier(s_suppkey) called supplier_pkey. I wonder why you don't have any of the primary indexes built because they should have been by default. In this case, it actually degenerates to a partly ripple join and partly wander join.

**Comment by solangepaz** [comment]
That was it, thank you :)
